dependencies:
  - name: prometheus-operator
    #repository: file://./helm-charts/prometheus-operator
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 5.5.1
    condition: prometheus.enabled
