apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alamedaservices.federatorai.containers.ai
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-delete-timeout": "120"
    "helm.sh/hook-weight": "50"
spec:
  group: federatorai.containers.ai
  names:
    kind: AlamedaService
    listKind: AlamedaServiceList
    plural: alamedaservices
    singular: alamedaservice
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
