apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: federatorai-operator
  namespace: federatorai
rules:
# following is taken from Federatorai-operator CSV v0.0.1 permissions section
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - endpoints
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get

